[build]
  base    = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

[context.production.environment]
  
  VITE_API_URL = "https://hms-3-0.onrender.com"
  VITE_DASHBOARD_URL = "https://hmsjammu.netlify.app/"
